### ISSUE TITLE
Documentation and Organization To-Do List

### ISSUE THREAD

**Issue by jasonrwang** [WKSu/Model-based-decision-making#8]
[![](https://i.ytimg.com/vi/PJhXVg2QisM/hqdefault.jpg)](https://www.youtube.com/watch?v=Ds6IwEKRLUU)

"Forked" from #6:

- [x] Organize root folder files into, possibly, `model` and any other necessary
- [ ] Continue documentation so the repo is pretty
- [ ] Ensure all style guides are properly followed
- [ ] Clean up the root folder further for files we don't need
- [ ] Clean up the `outcomes` folder and leave only the important ones
