### ISSUE TITLE
Analysis To-Do List

### ISSUE THREAD

**Issue by jasonrwang** [WKSu/Model-based-decision-making#9]
This is the list of things we need to do for analysis:

### Topics

- [x] Directed search (MORO)
- [x] Define robustness functions
- [x] Determine costs constraints (i.e. through scenario discovery, find necessary minimum RfR investment costs)
- [x] Determine costs of ecosystem services, social benefits, and other co-benefits

#### Report To-Dos

- [x] Verification / Validation of the model
- [x] Include multi-actor perspectives
 
### Technical/Code To-Dos
- [x] Change some scenario discovery functions into a method that we can run for analysis for different scenario/policy sets, worst- and best-cases (different quantiles), and different outcomes. – @WKSu

**Comment by jasonrwang** [comment]
@WKSu and I did 1 and 2 tonight; see ad32243

**Comment by WKSu** [comment]
Everything is finished!

**Comment by jasonrwang** [comment]
Looking at how to initialize `robust_optimization` (`AbstractGeneticAlgorithm.initialize` in `platypus`) with policies that we already have so we can check for hypervolume convergence. (Epsilon progress already converged).

**Comment by jasonrwang** [comment]
We're still bit unclear over how the hypervolume indicator works (see a0fad54).
